DROP DATABASE IF EXISTS geecoin;

CREATE DATABASE IF NOT EXISTS geecoin
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_general_ci;

USE geecoin;

DROP TABLE IF EXISTS incomes;
DROP TABLE IF EXISTS expenses;

CREATE TABLE IF NOT EXISTS incomes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    amount DECIMAL(10, 2) NOT NULL,
    date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS expenses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    amount DECIMAL(10, 2) NOT NULL,
    date DATE NOT NULL
);